<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;

class Providers7Porciento extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DB::table("providers_7porciento")->insert([
            ["super_plan_provider_id" => 1, "name" => 'Al Alemana Las Condes'],
            ["super_plan_provider_id" => 1, "name" => 'Alemana Las Condes'],
            ["super_plan_provider_id" => 1, "name" => 'Cl'],
            ["super_plan_provider_id" => 1, "name" => 'CLC'],
            ["super_plan_provider_id" => 1, "name" => 'CLC Universidad de Los Andes'],
            ["super_plan_provider_id" => 1, "name" => 'Las Condes'],
            ["super_plan_provider_id" => 1, "name" => 'Las Condes Imagenología'],
            ["super_plan_provider_id" => 1, "name" => 'Las Condes Laboratorio'],
            ["super_plan_provider_id" => 1, "name" => 'Las Condes Laboratorio e Imagenología'],
            ["super_plan_provider_id" => 1, "name" => 'Las Condes Traum'],
            ["super_plan_provider_id" => 1, "name" => 'Las Condes Universidad de Los Andes AMB PREF Norte'],
            ["super_plan_provider_id" => 1, "name" => 'Las CondesTraum'],
            ["super_plan_provider_id" => 1, "name" => 'TCLC'],
            ["super_plan_provider_id" => 3, "name" => 'Alemana'],
            ["super_plan_provider_id" => 3, "name" => 'Al Alemana Las Condes'],
            ["super_plan_provider_id" => 3, "name" => 'Alemana  AMB PREF Norte'],
            ["super_plan_provider_id" => 3, "name" => 'Alemana Las Condes'],
            ["super_plan_provider_id" => 3, "name" => 'Alemana Santiago'],
            ["super_plan_provider_id" => 3, "name" => 'Alemana Universidad de los Andes'],
            ["super_plan_provider_id" => 4, "name" => 'Apoquindo'],
            ["super_plan_provider_id" => 4, "name" => 'CSCA'],
            ["super_plan_provider_id" => 4, "name" => 'de Apoquindo'],
            ["super_plan_provider_id" => 4, "name" => 'MEDSy San Carlos de Apoquindo'],
            ["super_plan_provider_id" => 4, "name" => 'S'],
            ["super_plan_provider_id" => 4, "name" => 'San Carlos'],
            ["super_plan_provider_id" => 4, "name" => 'San Carlos de'],
            ["super_plan_provider_id" => 4, "name" => 'San Carlos de Apoquindo'],
            ["super_plan_provider_id" => 4, "name" => 'San Carlos de ApoquindoSanta María'],
            ["super_plan_provider_id" => 4, "name" => 'San Carlos deApoquindo'],
            ["super_plan_provider_id" => 4, "name" => 'San Carlos Traum'],
            ["super_plan_provider_id" => 4, "name" => 'SanCarlos'],
            ["super_plan_provider_id" => 4, "name" => 'UC San Carlos de Apoquindo'],
            ["super_plan_provider_id" => 6, "name" => 'Alemana Universidad de los Andes'],
            ["super_plan_provider_id" => 6, "name" => 'CLC Universidad de Los Andes'],
            ["super_plan_provider_id" => 6, "name" => 'Las Condes Universidad de Los Andes AMB PREF Norte'],
            ["super_plan_provider_id" => 6, "name" => 'Uandes'],
            ["super_plan_provider_id" => 6, "name" => 'Universidad Andes'],
            ["super_plan_provider_id" => 6, "name" => 'Universidad de Los Andes'],
            ["super_plan_provider_id" => 6, "name" => 'Universidad de Los AndesHOSP PREF Norte'],
            ["super_plan_provider_id" => 7, "name" => 'Biobío Santa María'],
            ["super_plan_provider_id" => 7, "name" => 'CMUC Santa María'],
            ["super_plan_provider_id" => 7, "name" => 'CSM'],
            ["super_plan_provider_id" => 7, "name" => 'María'],
            ["super_plan_provider_id" => 7, "name" => 'San Carlos de ApoquindoSanta María'],
            ["super_plan_provider_id" => 7, "name" => 'Santa'],
            ["super_plan_provider_id" => 7, "name" => 'Santa María'],
            ["super_plan_provider_id" => 7, "name" => 'Santa María AMB PREF Norte'],
            ["super_plan_provider_id" => 7, "name" => 'Santa María yMEDS'],
            ["super_plan_provider_id" => 7, "name" => 'Santa MaríaHOSP PREF Norte'],
            ["super_plan_provider_id" => 7, "name" => 'Santa MaríaVidaintegra'],
            ["super_plan_provider_id" => 7, "name" => 'SantaMaría'],
            ["super_plan_provider_id" => 7, "name" => 'sta'],
            ["super_plan_provider_id" => 7, "name" => 'Sta María'],
            ["super_plan_provider_id" => 8, "name" => 'ClIndisa'],
            ["super_plan_provider_id" => 8, "name" => 'en Indisa'],
            ["super_plan_provider_id" => 8, "name" => 'Hosp de la Red de Salud UC Christus Indisa'],
            ["super_plan_provider_id" => 8, "name" => 'Indisa'],
            ["super_plan_provider_id" => 8, "name" => 'Indisa AMB PREF Norte'],
            ["super_plan_provider_id" => 8, "name" => 'Indisa Hosp UC'],
            ["super_plan_provider_id" => 8, "name" => 'Indisa Imagenología'],
            ["super_plan_provider_id" => 8, "name" => 'Indisa Laboratorio'],
            ["super_plan_provider_id" => 8, "name" => 'IndisaHOSP PREF Norte'],
            ["super_plan_provider_id" => 9, "name" => 'MEDS'],
            ["super_plan_provider_id" => 9, "name" => 'MEDS yBupa Santiago'],
            ["super_plan_provider_id" => 9, "name" => 'MEDSy San Carlos de Apoquindo'],
            ["super_plan_provider_id" => 9, "name" => 'Santa María yMEDS'],
            ["super_plan_provider_id" => 10, "name" => 'Dávila RedSalud Vitacura'],
            ["super_plan_provider_id" => 10, "name" => 'Prov Pto VarasRedSalud Vitacura'],
            ["super_plan_provider_id" => 10, "name" => 'Redsalud Vitacura'],
            ["super_plan_provider_id" => 10, "name" => 'RedSalud Vitacura Bupa Santiago'],
            ["super_plan_provider_id" => 10, "name" => 'RedSalud Vitacura e Integramédica'],
            ["super_plan_provider_id" => 10, "name" => 'RedSalud Vitacura Indisa'],
            ["super_plan_provider_id" => 10, "name" => 'RedSalud Vitacura Indisa BUPA Santiago'],
            ["super_plan_provider_id" => 10, "name" => 'Vitacura'],
            ["super_plan_provider_id" => 10, "name" => 'RedSalud VitacuraIndisa'],
            ["super_plan_provider_id" => 10, "name" => 'RedSalud Vitacura Indisa'],
            ["super_plan_provider_id" => 10, "name" => 'RedSalud Vitacura Indisa BUPA Santiago'],
            ["super_plan_provider_id" => 10, "name" => 'RedSalud VitacuraIndisa'],
            ["super_plan_provider_id" => 11, "name" => 'Chosp UC'],
            ["super_plan_provider_id" => 11, "name" => 'Clinica UC'],
            ["super_plan_provider_id" => 11, "name" => 'Clínico UC'],
            ["super_plan_provider_id" => 11, "name" => 'ClUC'],
            ["super_plan_provider_id" => 11, "name" => 'en Hospital Clínico UC'],
            ["super_plan_provider_id" => 11, "name" => 'HopUC'],
            ["super_plan_provider_id" => 11, "name" => 'Hosp Clínico UC'],
            ["super_plan_provider_id" => 11, "name" => 'Hosp ClRed Salud UC Christus'],
            ["super_plan_provider_id" => 11, "name" => 'Hosp De la Red de Salud UC Christus'],
            ["super_plan_provider_id" => 11, "name" => 'Hosp de la Red de Salud UC Christus Indisa'],
            ["super_plan_provider_id" => 11, "name" => 'Hosp Red Salud UC Christus'],
            ["super_plan_provider_id" => 11, "name" => 'Hosp Red Salud UCChristus'],
            ["super_plan_provider_id" => 11, "name" => 'Hosp RedSalud UC Christus'],
            ["super_plan_provider_id" => 11, "name" => 'Hosp UC'],
            ["super_plan_provider_id" => 11, "name" => 'Hospital'],
            ["super_plan_provider_id" => 11, "name" => 'Hospital Clínico Universidad Católica'],
            ["super_plan_provider_id" => 11, "name" => 'Hospital ClínicoUC'],
            ["super_plan_provider_id" => 11, "name" => 'Hospital UC'],
            ["super_plan_provider_id" => 11, "name" => 'Hospital Universidad Católica'],
            ["super_plan_provider_id" => 11, "name" => 'HospUC'],
            ["super_plan_provider_id" => 11, "name" => 'Indisa Hosp UC'],
            ["super_plan_provider_id" => 11, "name" => 'UC'],
            ["super_plan_provider_id" => 11, "name" => 'UC Christus'],
            ["super_plan_provider_id" => 11, "name" => 'UC San Carlos de Apoquindo'],
            ["super_plan_provider_id" => 14, "name" => 'Bupa Reñaca'],
            ["super_plan_provider_id" => 14, "name" => 'BupaReñaca'],
            ["super_plan_provider_id" => 14, "name" => 'CBR'],
            ["super_plan_provider_id" => 14, "name" => 'Clinica Bupa Reñaca COPAGO UF'],
            ["super_plan_provider_id" => 14, "name" => 'Reñaca'],
            ["super_plan_provider_id" => 14, "name" => 'Reñaca(Hab Doble)'],
            ["super_plan_provider_id" => 14, "name" => 'Reñaca(ind)'],
            ["super_plan_provider_id" => 14, "name" => 'Santiago Bupa Reñaca'],
            ["super_plan_provider_id" => 14, "name" => 'TBUPA Reñaca'],
            ["super_plan_provider_id" => 15, "name" => 'BUPA Santiago'],
            ["super_plan_provider_id" => 15, "name" => 'Bupa Santiago COPAGO UF  Hosp Quinta'],
            ["super_plan_provider_id" => 15, "name" => 'BUPA Stgp'],
            ["super_plan_provider_id" => 15, "name" => 'BupaSantiago'],
            ["super_plan_provider_id" => 15, "name" => 'Hosp UCHBupa Santiago'],
            ["super_plan_provider_id" => 15, "name" => 'Hosp Universidad de ChileBupa Santiago'],
            ["super_plan_provider_id" => 15, "name" => 'IM Bupa Santiago'],
            ["super_plan_provider_id" => 15, "name" => 'Integramedica Sonorad Clinica Bupa Santiago AMB preferente Quinta'],
            ["super_plan_provider_id" => 15, "name" => 'MEDS yBupa Santiago'],
            ["super_plan_provider_id" => 15, "name" => 'RedSalud Vitacura Bupa Santiago'],
            ["super_plan_provider_id" => 15, "name" => 'RedSalud Vitacura Indisa BUPA Santiago'],
            ["super_plan_provider_id" => 16, "name" => 'ClCordillera'],
            ["super_plan_provider_id" => 16, "name" => 'ClDávilaAndes Salud Concepción Cordillera'],
            ["super_plan_provider_id" => 16, "name" => 'Cordillera'],
            ["super_plan_provider_id" => 19, "name" => 'Ant'],
            ["super_plan_provider_id" => 19, "name" => 'Antofagasta'],
            ["super_plan_provider_id" => 19, "name" => 'Antofagasta Imagenología'],
            ["super_plan_provider_id" => 19, "name" => 'BUPA'],
            ["super_plan_provider_id" => 19, "name" => 'BUPA Ant'],
            ["super_plan_provider_id" => 19, "name" => 'Bupa Antofagasta'],
            ["super_plan_provider_id" => 19, "name" => 'BUPAAnt'],
            ["super_plan_provider_id" => 20, "name" => 'Ciudad'],
            ["super_plan_provider_id" => 20, "name" => 'Ciudad del M ar'],
            ["super_plan_provider_id" => 20, "name" => 'Ciudad del Mar'],
            ["super_plan_provider_id" => 20, "name" => 'Ciudad delM ar'],
            ["super_plan_provider_id" => 20, "name" => 'del Mar'],
            ["super_plan_provider_id" => 22, "name" => 'Los Andes de LA'],
            ["super_plan_provider_id" => 22, "name" => 'Andes Chillán'],
            ["super_plan_provider_id" => 22, "name" => 'Los Andes de Ch'],
            ["super_plan_provider_id" => 22, "name" => 'Los Andes de Ch'],
            ["super_plan_provider_id" => 22, "name" => 'Los Andes de Ch'],
            ["super_plan_provider_id" => 22, "name" => 'Los Andes deLA'],
            ["super_plan_provider_id" => 22, "name" => 'Los Andes Los Angeles'],
            ["super_plan_provider_id" => 22, "name" => 'Los Andesde Ch'],
            ["super_plan_provider_id" => 22, "name" => 'RedSaud ProvidenciaAndes Chillán'],
            ["super_plan_provider_id" => 23, "name" => 'Sanatorio Alemán'],
            ["super_plan_provider_id" => 24, "name" => 'Hosp del Sur'],
            ["super_plan_provider_id" => 25, "name" => 'Alemana de Valdivia'],
            ["super_plan_provider_id" => 25, "name" => 'Valdivia'],
            ["super_plan_provider_id" => 26, "name" => 'Alemana de'],
            ["super_plan_provider_id" => 26, "name" => 'Alemana de Osorno'],
            ["super_plan_provider_id" => 26, "name" => 'Alemana Osorno'],
            ["super_plan_provider_id" => 27, "name" => 'Hosp de Magallanes'],
            ["super_plan_provider_id" => 27, "name" => 'Magallanes'],
            ["super_plan_provider_id" => 27, "name" => 'RedSalud Magallanes'],
            ["super_plan_provider_id" => 27, "name" => 'TRedsalud Magallanes'],
            ["super_plan_provider_id" => 28, "name" => 'Clinica Los Carrera'],
            ["super_plan_provider_id" => 28, "name" => 'Los Carrera'],
            ["super_plan_provider_id" => 28, "name" => 'Los Carrera(ind)'],
            ["super_plan_provider_id" => 29, "name" => 'T'],
            ["super_plan_provider_id" => 29, "name" => 'Tarapacá'],
            ["super_plan_provider_id" => 29, "name" => 'Tarpacá'],
            ["super_plan_provider_id" => 30, "name" => 'Integramedica RedSalud Providencia RedSalud Santiago'],
            ["super_plan_provider_id" => 30, "name" => 'Prov'],
            ["super_plan_provider_id" => 30, "name" => 'Prov e Iqq'],
            ["super_plan_provider_id" => 30, "name" => 'Prov Pto Varas'],
            ["super_plan_provider_id" => 30, "name" => 'Prov Pto VarasRedSalud Vitacura'],
            ["super_plan_provider_id" => 30, "name" => 'Providencia'],
            ["super_plan_provider_id" => 30, "name" => 'RedSalud Prov'],
            ["super_plan_provider_id" => 30, "name" => 'RedSalud Providencia'],
            ["super_plan_provider_id" => 30, "name" => 'RedSalud Providencia RedSalud Santiago Dávila Hospital Clínico Universidad de Chile Vespucio'],
            ["super_plan_provider_id" => 30, "name" => 'RedSalud Santiago  yProv'],
            ["super_plan_provider_id" => 30, "name" => 'RedSaud Providencia'],
            ["super_plan_provider_id" => 30, "name" => 'RedSaud ProvidenciaAndes Chillán'],
            ["super_plan_provider_id" => 30, "name" => 'RedSaudProvidencia'],
            ["super_plan_provider_id" => 31, "name" => 'Andes Salud ConcepciónDávila'],
            ["super_plan_provider_id" => 31, "name" => 'C'],
            ["super_plan_provider_id" => 31, "name" => 'ClDáv'],
            ["super_plan_provider_id" => 31, "name" => 'ClDávila'],
            ["super_plan_provider_id" => 31, "name" => 'ClDávilaAndes Salud Concepción Cordillera'],
            ["super_plan_provider_id" => 31, "name" => 'Dáv'],
            ["super_plan_provider_id" => 31, "name" => 'Dávi'],
            ["super_plan_provider_id" => 31, "name" => 'Dávila'],
            ["super_plan_provider_id" => 31, "name" => 'Dávila  AMB PREF Norte'],
            ["super_plan_provider_id" => 31, "name" => 'Dávila RedSalud Vitacura'],
            ["super_plan_provider_id" => 31, "name" => 'Dávila Vespucio'],
            ["super_plan_provider_id" => 31, "name" => 'Dávila yVespucio'],
            ["super_plan_provider_id" => 31, "name" => 'en Dávila'],
            ["super_plan_provider_id" => 31, "name" => 'FUSA C Dáv'],
            ["super_plan_provider_id" => 31, "name" => 'Hosp Universidad de Chile Dávila'],
            ["super_plan_provider_id" => 31, "name" => 'Hosp Universidad de ChileDávila'],
            ["super_plan_provider_id" => 31, "name" => 'HUCH Dávila'],
            ["super_plan_provider_id" => 31, "name" => 'IM Dávila'],
            ["super_plan_provider_id" => 31, "name" => 'Integramedica Dávila'],
            ["super_plan_provider_id" => 31, "name" => 'Pto Varas Dávila'],
            ["super_plan_provider_id" => 31, "name" => 'RedSalud Rancagua Dávila'],
            ["super_plan_provider_id" => 31, "name" => 'TDávila'],
            ["super_plan_provider_id" => 32, "name" => 'ClVespucio'],
            ["super_plan_provider_id" => 32, "name" => 'Dávila Vespucio'],
            ["super_plan_provider_id" => 32, "name" => 'Dávila yVespucio'],
            ["super_plan_provider_id" => 32, "name" => 'RedSalud Providencia RedSalud Santiago Dávila Hospital Clínico Universidad de Chile Vespucio'],
            ["super_plan_provider_id" => 32, "name" => 'Vesp'],
            ["super_plan_provider_id" => 32, "name" => 'Vesp Copago Máximo por Evento de  UF'],
            ["super_plan_provider_id" => 32, "name" => 'Vespucio'],
            ["super_plan_provider_id" => 33, "name" => 'Hosp Cl'],
            ["super_plan_provider_id" => 33, "name" => 'H Universidad de Chile'],
            ["super_plan_provider_id" => 33, "name" => 'Hosp Clínico Universidad de Chile'],
            ["super_plan_provider_id" => 33, "name" => 'Hosp ClUniversidad Chile'],
            ["super_plan_provider_id" => 33, "name" => 'Hosp UCH'],
            ["super_plan_provider_id" => 33, "name" => 'Hosp UCHBupa Santiago'],
            ["super_plan_provider_id" => 33, "name" => 'Hosp UChile'],
            ["super_plan_provider_id" => 33, "name" => 'Hosp Universidad Chile'],
            ["super_plan_provider_id" => 33, "name" => 'Hosp Universidad de Chile'],
            ["super_plan_provider_id" => 33, "name" => 'Hosp Universidad de Chile Dávila'],
            ["super_plan_provider_id" => 33, "name" => 'Hosp Universidad de ChileBupa Santiago'],
            ["super_plan_provider_id" => 33, "name" => 'Hosp Universidad de ChileDávila'],
            ["super_plan_provider_id" => 33, "name" => 'Hospital Clínico UC'],
            ["super_plan_provider_id" => 33, "name" => 'Hospital Clínico UC e Integramédica'],
            ["super_plan_provider_id" => 33, "name" => 'HospitalClínico Universidad de Chile'],
            ["super_plan_provider_id" => 33, "name" => 'HospUniversidad Chile'],
            ["super_plan_provider_id" => 33, "name" => 'HospUniversidad de Chile'],
            ["super_plan_provider_id" => 33, "name" => 'HUCH'],
            ["super_plan_provider_id" => 33, "name" => 'HUCH Dávila'],
            ["super_plan_provider_id" => 33, "name" => 'Integramedica Hosp Universidad de Chile'],
            ["super_plan_provider_id" => 33, "name" => 'RedSalud Providencia RedSalud Santiago Dávila Hospital Clínico Universidad de Chile Vespucio'],
            ["super_plan_provider_id" => 33, "name" => 'Hospital Clínico Universidad de Chile'],
            ["super_plan_provider_id" => 33, "name" => 'Universidad Chile'],
            ["super_plan_provider_id" => 34, "name" => 'San José'],
            ["super_plan_provider_id" => 34, "name" => 'San José Arica'],
            ["super_plan_provider_id" => 34, "name" => 'San José de Arica'],
            ["super_plan_provider_id" => 35, "name" => 'El Loa'],
            ["super_plan_provider_id" => 35, "name" => 'Loa'],
            ["super_plan_provider_id" => 36, "name" => 'La Portada'],
            ["super_plan_provider_id" => 36, "name" => 'Portada'],
            ["super_plan_provider_id" => 39, "name" => 'Atacama'],
            ["super_plan_provider_id" => 39, "name" => 'RCR'],
            ["super_plan_provider_id" => 39, "name" => 'RCR Atacama'],
            ["super_plan_provider_id" => 40, "name" => 'ELQ'],
            ["super_plan_provider_id" => 40, "name" => 'Elqui'],
            ["super_plan_provider_id" => 40, "name" => 'Elqui e Iqq'],
            ["super_plan_provider_id" => 40, "name" => 'Habitación Doble en RedSalud Elqui'],
            ["super_plan_provider_id" => 40, "name" => 'RedSald Elqui'],
            ["super_plan_provider_id" => 40, "name" => 'RedSalud Elqui'],
            ["super_plan_provider_id" => 40, "name" => 'RedSaud Elqui'],
            ["super_plan_provider_id" => 41, "name" => 'Clinica Red Salud Valparaiso'],
            ["super_plan_provider_id" => 41, "name" => 'Redsalud Valp'],
            ["super_plan_provider_id" => 41, "name" => 'RedSalud Valparaíso'],
            ["super_plan_provider_id" => 41, "name" => 'RedSalud Vaparaíso'],
            ["super_plan_provider_id" => 41, "name" => 'RedSaud Valparaíso'],
            ["super_plan_provider_id" => 41, "name" => 'Valp'],
            ["super_plan_provider_id" => 41, "name" => 'Valparaíso'],
            ["super_plan_provider_id" => 42, "name" => 'Hosp Viña del Mar'],
            ["super_plan_provider_id" => 42, "name" => 'Hospital CL Viña del Mar'],
            ["super_plan_provider_id" => 44, "name" => 'FUSA C Dáv'],
            ["super_plan_provider_id" => 44, "name" => 'FUSA(doble)'],
            ["super_plan_provider_id" => 44, "name" => 'FUSA(ind)'],
            ["super_plan_provider_id" => 44, "name" => 'FUSAT'],
            ["super_plan_provider_id" => 44, "name" => 'Hosp FUSAT'],
            ["super_plan_provider_id" => 45, "name" => 'Lircay'],
            ["super_plan_provider_id" => 46, "name" => 'Andes Chillán'],
            ["super_plan_provider_id" => 46, "name" => 'Chillán'],
            ["super_plan_provider_id" => 46, "name" => 'Las Amapolas Chillán'],
            ["super_plan_provider_id" => 46, "name" => 'Los Andes Chillán'],
            ["super_plan_provider_id" => 46, "name" => 'RedSaud ProvidenciaAndes Chillán'],
            ["super_plan_provider_id" => 47, "name" => 'Universidad de Conce'],
            ["super_plan_provider_id" => 47, "name" => 'Universitaria de Concepción'],
            ["super_plan_provider_id" => 48, "name" => 'Bio Bio'],
            ["super_plan_provider_id" => 48, "name" => 'Biobío'],
            ["super_plan_provider_id" => 48, "name" => 'Biobío Santa María'],
            ["super_plan_provider_id" => 48, "name" => 'Santa María Biobío'],
            ["super_plan_provider_id" => 49, "name" => 'Alemana de Temuco'],
            ["super_plan_provider_id" => 49, "name" => 'ClAlemana de Temuco'],
            ["super_plan_provider_id" => 49, "name" => 'Temuco'],
            ["super_plan_provider_id" => 50, "name" => 'Centros Médicos RedSaludRedSaud Mayor'],
            ["super_plan_provider_id" => 50, "name" => 'Clinica RedSalud Mayor de Temuco'],
            ["super_plan_provider_id" => 50, "name" => 'Mayor'],
            ["super_plan_provider_id" => 50, "name" => 'Mayor de Temuco'],
            ["super_plan_provider_id" => 50, "name" => 'Redsalud Mayor'],
            ["super_plan_provider_id" => 50, "name" => 'RedSalud Mayor de'],
            ["super_plan_provider_id" => 50, "name" => 'RedSalud Mayor de Temco'],
            ["super_plan_provider_id" => 50, "name" => 'RedSalud Mayor de Temuco'],
            ["super_plan_provider_id" => 50, "name" => 'RedSaud Mayor'],
            ["super_plan_provider_id" => 51, "name" => 'Prov Pto Varas'],
            ["super_plan_provider_id" => 51, "name" => 'Prov Pto VarasRedSalud Vitacura'],
            ["super_plan_provider_id" => 51, "name" => 'Pto Varas'],
            ["super_plan_provider_id" => 51, "name" => 'Pto Varas Dávila'],
            ["super_plan_provider_id" => 51, "name" => 'Pto Varas RedSalud Santiago'],
            ["super_plan_provider_id" => 51, "name" => 'Puerto Varas'],
            ["super_plan_provider_id" => 51, "name" => 'Puerto Varas Laboratorio'],
            ["super_plan_provider_id" => 51, "name" => 'VitacuraPto Varas'],
            ["super_plan_provider_id" => 52, "name" => 'Clinica Universitaria de Puerto Montt'],
            ["super_plan_provider_id" => 52, "name" => 'Univ Pto Montt'],
            ["super_plan_provider_id" => 52, "name" => 'Univ Pto Montt RedSaud Santiago'],
            ["super_plan_provider_id" => 52, "name" => 'Universidad de Pto Montt'],
            ["super_plan_provider_id" => 52, "name" => 'Universidad Pto Montt'],
            ["super_plan_provider_id" => 52, "name" => 'Universidad PtoMontt'],
            ["super_plan_provider_id" => 52, "name" => 'Universidad Puerto Montt'],
            ["super_plan_provider_id" => 52, "name" => 'Universitaria'],
            ["super_plan_provider_id" => 52, "name" => 'Universitaria de Puerto Montt'],
            ["super_plan_provider_id" => 52, "name" => 'Universitaria Puerto MonttRedSaud Santiago'],
            ["super_plan_provider_id" => 53, "name" => 'de Puerto Montt'],
            ["super_plan_provider_id" => 53, "name" => 'Puerto Montt'],
            ["super_plan_provider_id" => 54, "name" => 'Andes Salud ConcepciónRedSaud Santiago'],
            ["super_plan_provider_id" => 54, "name" => 'ClínicasRedSalud Santiago'],
            ["super_plan_provider_id" => 54, "name" => 'Integramedica RedSalud Providencia RedSalud Santiago'],
            ["super_plan_provider_id" => 54, "name" => 'Integramedica ReSalud Santiago'],
            ["super_plan_provider_id" => 54, "name" => 'Pto Varas RedSalud Santiago'],
            ["super_plan_provider_id" => 54, "name" => 'RedSalud Providencia RedSalud Santiago Dávila Hospital Clínico Universidad de Chile Vespucio'],
            ["super_plan_provider_id" => 54, "name" => 'Redsalud Santiago'],
            ["super_plan_provider_id" => 54, "name" => 'RedSalud Santiago  yProv'],
            ["super_plan_provider_id" => 54, "name" => 'RedSaud Santiago'],
            ["super_plan_provider_id" => 54, "name" => 'ReSalud Santiago'],
            ["super_plan_provider_id" => 54, "name" => 'Santiago'],
            ["super_plan_provider_id" => 54, "name" => 'Santiago Bupa Reñaca'],
            ["super_plan_provider_id" => 54, "name" => 'Univ Pto Montt RedSaud Santiago'],
            ["super_plan_provider_id" => 54, "name" => 'Universitaria Puerto MonttRedSaud Santiago'],
            ["super_plan_provider_id" => 55, "name" => 'Juan Pablo II'],
            ["super_plan_provider_id" => 57, "name" => 'Hosp del Profesor'],
            ["super_plan_provider_id" => 57, "name" => 'Hosp Profesor'],
            ["super_plan_provider_id" => 57, "name" => 'HospDel Profesor'],
            ["super_plan_provider_id" => 57, "name" => 'Hospítal del Profesor'],
            ["super_plan_provider_id" => 57, "name" => 'HospProfesor'],
            ["super_plan_provider_id" => 58, "name" => 'Hosp Parroquial'],
            ["super_plan_provider_id" => 58, "name" => 'Hosp Parroquial San Bernardo'],
            ["super_plan_provider_id" => 58, "name" => 'HospParroquial'],
            ["super_plan_provider_id" => 58, "name" => 'Parroquial'],
            ["super_plan_provider_id" => 60, "name" => 'Elqui e Iqq'],
            ["super_plan_provider_id" => 60, "name" => 'Prov e Iqq'],
            ["super_plan_provider_id" => 60, "name" => 'Redsalud Iqq'],
            ["super_plan_provider_id" => 60, "name" => 'RedSalud Iquique'],
            ["super_plan_provider_id" => 60, "name" => 'RedSaud Iquique'],
            ["super_plan_provider_id" => 63, "name" => 'Isamédica'],
            ["super_plan_provider_id" => 64, "name" => 'Rancagua'],
            ["super_plan_provider_id" => 64, "name" => 'Redsalud Rancagua'],
            ["super_plan_provider_id" => 64, "name" => 'RedSalud Rancagua Dávila'],
            ["super_plan_provider_id" => 64, "name" => 'RedSaud Rancagua'],
            ["super_plan_provider_id" => 65, "name" => 'Amapolas'],
            ["super_plan_provider_id" => 65, "name" => 'Las Amapolas Chillán'],
            ["super_plan_provider_id" => 68, "name" => 'Centor Red UC'],
            ["super_plan_provider_id" => 68, "name" => 'Centro Red UC'],
            ["super_plan_provider_id" => 68, "name" => 'Centro Red UC Imagenología'],
            ["super_plan_provider_id" => 68, "name" => 'Centro Red UC Laboratorio'],
            ["super_plan_provider_id" => 68, "name" => 'Centros Médicos UC Christus'],
            ["super_plan_provider_id" => 68, "name" => 'Centros Red U'],
            ["super_plan_provider_id" => 68, "name" => 'Centros Red UC'],
            ["super_plan_provider_id" => 68, "name" => 'Centros Red UC Imagenología'],
            ["super_plan_provider_id" => 68, "name" => 'Centros Red UC Laboratorio'],
            ["super_plan_provider_id" => 68, "name" => 'CentrosMédicos UC Christus'],
            ["super_plan_provider_id" => 68, "name" => 'Red de Centros Medicos UC Christus'],
            ["super_plan_provider_id" => 68, "name" => 'RED UC'],
            ["super_plan_provider_id" => 68, "name" => 'Red UC Integramedica Traum'],
            ["super_plan_provider_id" => 68, "name" => 'Red UC Traum'],
            ["super_plan_provider_id" => 69, "name" => 'Integramedica Hosp Universidad de Chile'],
            ["super_plan_provider_id" => 69, "name" => 'Hospital Clínico UC e Integramédica'],
            ["super_plan_provider_id" => 69, "name" => 'IIntegramedica'],
            ["super_plan_provider_id" => 69, "name" => 'Integr'],
            ["super_plan_provider_id" => 69, "name" => 'Integra'],
            ["super_plan_provider_id" => 69, "name" => 'Integramédica'],
            ["super_plan_provider_id" => 69, "name" => 'Integramedica Dávila'],
            ["super_plan_provider_id" => 69, "name" => 'Integramedica RedSalud Providencia RedSalud Santiago'],
            ["super_plan_provider_id" => 69, "name" => 'Integramedica ReSalud Santiago'],
            ["super_plan_provider_id" => 69, "name" => 'Integramedica Sonorad Clinica Bupa Santiago AMB preferente Quinta'],
            ["super_plan_provider_id" => 69, "name" => 'Integramedica Traum'],
            ["super_plan_provider_id" => 69, "name" => 'IntegramedicaM'],
            ["super_plan_provider_id" => 69, "name" => 'Intregramédica'],
            ["super_plan_provider_id" => 69, "name" => 'Red UC Integramedica Traum'],
            ["super_plan_provider_id" => 69, "name" => 'RedSalud Vitacura e Integramédica'],
            ["super_plan_provider_id" => 70, "name" => 'Centro Médico Integral Medicien'],
            ["super_plan_provider_id" => 70, "name" => 'Centro Médico Medicien'],
            ["super_plan_provider_id" => 70, "name" => 'Medicien'],
            ["super_plan_provider_id" => 70, "name" => 'sin tope Centro Médico Medicien'],
            ["super_plan_provider_id" => 73, "name" => 'Centros Médicos'],
            ["super_plan_provider_id" => 73, "name" => 'Centros Médicos Arauco Centros Médicos RedSalud'],
            ["super_plan_provider_id" => 73, "name" => 'Centros Médicos Redsald'],
            ["super_plan_provider_id" => 73, "name" => 'Centros Médicos Redsalud'],
            ["super_plan_provider_id" => 73, "name" => 'Centros Médicos RedSaludRedSaud Mayor'],
            ["super_plan_provider_id" => 73, "name" => 'Centros MédicosRedSalud'],
            ["super_plan_provider_id" => 73, "name" => 'CentrosMédicos Redsalud'],
            ["super_plan_provider_id" => 73, "name" => 'Redsalud'],
            ["super_plan_provider_id" => 74, "name" => 'Centros Médicos Vidaintegra'],
            ["super_plan_provider_id" => 74, "name" => 'Santa MaríaVidaintegra'],
            ["super_plan_provider_id" => 74, "name" => 'VI'],
            ["super_plan_provider_id" => 74, "name" => 'Vidaintegra'],
            ["super_plan_provider_id" => 75, "name" => 'Centros Médicos Arauco'],
            ["super_plan_provider_id" => 75, "name" => 'Centros Médicos Arauco Centros Médicos RedSalud'],
            ["super_plan_provider_id" => 78, "name" => 'Integramedica Sonorad Clinica Bupa Santiago AMB preferente Quinta'],
            ["super_plan_provider_id" => 78, "name" => 'Sonorad'],
            ["super_plan_provider_id" => 79, "name" => 'Andes Salud Concepción'],
            ["super_plan_provider_id" => 79, "name" => 'Andes Salud ConcepciónDávila'],
            ["super_plan_provider_id" => 79, "name" => 'Andes Salud ConcepciónRedSaud Santiago'],
            ["super_plan_provider_id" => 79, "name" => 'ClDávilaAndes Salud Concepción Cordillera'],
            ["super_plan_provider_id" => 80, "name" => 'Centromed'],
            ["super_plan_provider_id" => 81, "name" => 'Clinica Los Leones'],
        ]);
    }
}
